### ISSUE TITLE
Lositan

### ISSUE THREAD

**Issue by Silvia-lme** [tiagoantao/lositan#9]
When I am running software LOSITAN I am getting this error:
Segmentation fault (core dumped)
Unhandled exception in thread started by <function endRunDatacal at 0x3>
Traceback (most recent call last):
  File "/home/a/.lositan/Main.py", line 341, in endRunDatacal
    fst, sampSize = fdc.run_datacal(data_dir = lpath)
  File "/media/a/PRACOVNI/Lositan/build/install/lositan/lib/Lib/Bio/PopGen/FDist/Controller.py", line 94, in run_datacal
    fst = my_float(fst_line[4])
IndexError: index out of range: 4

Please advise if there is known any solution of the issue?

 Many thanks,.

**Comment by tiagoantao** [comment]
Lositan is not supported anymore.
